instrumentation:
  root: src
  include-all-sources: true
  default-excludes: true
  excludes: ['**/*.spec.js', '**/*.specdef.js', '**/index.js']
  es-modules: true
extensions:
    - .js
reporting:
  reports:
    - text
    - lcov
